### ISSUE TITLE
StringIndexOutOfBoundsException in the IntelliJ plugin

### ISSUE THREAD

**Issue by bjansen** [manifold-systems/manifold#107]
**Describe the bug**
A `StringIndexOutOfBoundsException` happens when editing a `package` statement.

**To Reproduce**
1. Create a fresh new Maven project and add the `manifold-all` dependency
2. Create a new extension class in `src/main/java`, type a random name and leave the default extended type (in my case `Messages in messages.properties`
3. Realize that your not interested in extending this class at all, so decide to extend `java.lang.String` instead
4. Remove parts of the `package` statement so that it reads `package foo.extensions.;`

**Expected behavior**
No exception :)

**Desktop (please complete the following information):**
```
IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```
- Manifold version: 2019.1.7
- Manifold IntelliJ plugin version: 2019.1.7

**Stack trace**
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at manifold.ij.extensions.ExtensionMethodUsageSearcher.getExtendedFqn(ExtensionMethodUsageSearcher.java:176)
	at manifold.ij.extensions.ExtensionMethodUsageSearcher.lambda$processQuery$1(ExtensionMethodUsageSearcher.java:121)
	at manifold.ij.extensions.ExtensionMethodUsageSearcher.resolveInReadAction(ExtensionMethodUsageSearcher.java:186)
	at manifold.ij.extensions.ExtensionMethodUsageSearcher.processQuery(ExtensionMethodUsageSearcher.java:90)
	at manifold.ij.extensions.ExtensionMethodUsageSearcher.processQuery(ExtensionMethodUsageSearcher.java:36)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:31)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:66)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:70)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:43)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:55)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:45)
	at com.intellij.find.findUsages.JavaFindUsagesHelper.addElementUsages(JavaFindUsagesHelper.java:478)
	at com.intellij.find.findUsages.JavaFindUsagesHelper.processElementUsages(JavaFindUsagesHelper.java:117)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.processUsages(UnusedSymbolUtil.java:254)
	at com.intellij.codeInspection.visibility.AccessCanBeTightenedInspection$MyVisitor.suggestLevel(AccessCanBeTightenedInspection.java:195)
	at com.intellij.codeInspection.visibility.AccessCanBeTightenedInspection$MyVisitor.checkMember(AccessCanBeTightenedInspection.java:105)
	at com.intellij.codeInspection.visibility.AccessCanBeTightenedInspection$MyVisitor.visitMethod(AccessCanBeTightenedInspection.java:88)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:286)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:295)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:260)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by bjansen** [comment]
BTW, is the IntelliJ plugin open source? I couldn't find the repo.

**Comment by rsmckinney** [comment]
Hi @bjansen.  Thanks for reporting this issue!  Does IJ recover from the exception for you?  Or does it require a reopen of the project?

As you have discovered the IJ plugin is currently not open source, it is maintained as a private project on github.  Licensed copies of the source are available.

**Comment by bjansen** [comment]
Yes it recovers without any problem.

I was asking if the plugin is open source to see if I could provide a PR, but I can't :).

**Comment by rsmckinney** [comment]
Yeah, sorry about that. I'll probably make a version of the repo public at some point.

**Comment by bjansen** [comment]
Oh ok I didn't see the plugin is not free. I guess I started a 30 days trial without even realizing it...

**Comment by rsmckinney** [comment]
The Manifold plugin is currently free for use with IntelliJ Community Edition, which is probably why you didn't notice anything re license.  Also it's free for students and faculty members.  There's a ton of [discounts and special programs](https://sales.jetbrains.com/hc/en-gb/sections/201563069-Discounts-and-Special-Programs) available from JetBrains.  Worth checking out.
