### ISSUE TITLE
IntelliJ debugging causes IDE Internal Error

### ISSUE THREAD

**Issue by OxygeneIV** [manifold-systems/manifold#109]
Getting the following "IDE Internal  Error" during debug of project using the -ext and -collections Manifolds. Have used the two latest Intellij/Manifold - versions but the error remains.   

1. Start a debug session 
2. IDE error appears within a few seconds

- OS Type & Version:  Win10
- Java/JDK version: 1.8
- IntelliJ IDEA version: 2019.2
- Manifold version: 2019.1.8
- Manifold IntelliJ plugin version:  2019.1.8

**Stack trace**

java.lang.Throwable: Must be executed under progress indicator: com.intellij.openapi.progress.EmptyProgressIndicator@20466b43. Please see e.g. ProgressManager.runProcess()
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.assertUnderProgress(CoreProgressManager.java:924)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processFilesConcurrentlyDespiteWriteActions(PsiSearchHelperImpl.java:333)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processPsiFileRoots(PsiSearchHelperImpl.java:299)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processCandidates(PsiSearchHelperImpl.java:721)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequestsOptimized(PsiSearchHelperImpl.java:701)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:599)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:24)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:114)
	at com.intellij.util.MergeQuery.processResults(MergeQuery.java:26)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:114)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:40)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:91)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:83)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:27)
	at manifold.ij.extensions.ResourceToManifoldUtil.findJavaElementsFor(ResourceToManifoldUtil.java:196)
	at manifold.ij.extensions.ResourceToManifoldUtil.findJavaElementsFor(ResourceToManifoldUtil.java:114)
	at manifold.ij.extensions.ManifoldFindUsagesHandlerFactory.canFindUsages(ManifoldFindUsagesHandlerFactory.java:41)
	at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:161)
	at com.intellij.find.findUsages.FindUsagesManager.getFindUsagesHandler(FindUsagesManager.java:155)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:169)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:160)
	at com.intellij.debugger.impl.DebuggerContextUtil.findNearest(DebuggerContextUtil.java:85)
	at com.intellij.debugger.engine.DefaultSourcePositionProvider.getSourcePositionForField(DefaultSourcePositionProvider.java:124)
	at com.intellij.debugger.engine.DefaultSourcePositionProvider.computeSourcePosition(DefaultSourcePositionProvider.java:47)
	at com.intellij.debugger.engine.SourcePositionProvider.lambda$getSourcePosition$0(SourcePositionProvider.java:47)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at one.util.streamex.AbstractStreamEx.findFirst(AbstractStreamEx.java:462)
	at com.intellij.debugger.engine.SourcePositionProvider.getSourcePosition(SourcePositionProvider.java:49)
	at com.intellij.debugger.engine.JavaValue$4.lambda$contextAction$0(JavaValue.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at com.intellij.debugger.engine.JavaValue$4.contextAction(JavaValue.java:396)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:57)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:43)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:151)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:29)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:138)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:19)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.lambda$run$0(InvokeThread.java:49)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rsmckinney** [comment]
in process

**Comment by rsmckinney** [comment]
@OxygeneIV. Thanks for reporting this issue!  A fix will be available in the next release, which is awaiting JetBrains Marketplace processing, probably EOD July 29.
