### ISSUE TITLE
Incompatible with Gradle 5.5.1 & 5.6: They use different JavaFileManager impl.

### ISSUE THREAD

**Issue by StrangeNoises** [manifold-systems/manifold#114]
**Describe the bug**
Trying to set up Manifold in a simple Gradle project, not even yet trying to actually *use* any features of it, just doing the `build.gradle` changes as per the manifold-exceptions readme; fails to build with:

```
Caused by: java.lang.RuntimeException: Method 'getLocationAsPaths' not found
        at manifold.util.ReflectUtil.method(ReflectUtil.java:160)
        at manifold.internal.javac.JavacFileManagerBridge.getLocationAsPaths(JavacFileManagerBridge.java:132)
        ... 43 more
```

(Full stacktrace later for completion's sake but probably not much of it is relevant.)

Also fails with previous version of manifold-all. (there is no previous version of manifold-exceptions!)

Presumably the JavacFileManager now in use does not implement StandardJavaFileManager and so does not inherit its default method getLocationAsPaths.

Tested initially with Gradle 5.6, also encountered problem on Gradle 5.5.1, but on Gradle 5.5 it works without reported errors.

Platform: Java 11.0.4 on Linux x64 in all cases.

**To Reproduce**
1. Create a trivially simple gradle java project and apply changes as per instructions in the manifold-exceptions readme for Java 11+. In fact I started by trying it on a complex multi-project but when that failed, fell back to first trying to add it to a very simple java library with no dependencies, and had the same problem. Its entire `build.gradle` follows (this is after updating it to more closely match the example):

```groovy
plugins {
    id 'java'
}

group 'uk.co.merus.toolbox'
version '1.0-SNAPSHOT'

targetCompatibility = 11
sourceCompatibility = 11

repositories {
    jcenter()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.compilerArgs += [
        '-Xlint:unchecked,deprecation',
        '-Xplugin:Manifold'
    ]
    options.fork = true
}

dependencies {
    compile group: 'systems.manifold', name: 'manifold-exceptions', version: '2019.1.11'

    // Add manifold-exceptions to -processorpath for javac
    annotationProcessor group: 'systems.manifold', name: 'manifold-exceptions', version: '2019.1.11'
}
```

2. Set gradle wrapper to 5.6 or 5.5.1.

3. Try to build with gradlew

4. Observe the build failing as per the stack trace pasted at the bottom.

**Expected behavior**

Expected behaviour is met if using Gradle 5.5 and probably earlier.

1. Set the gradle wrapper to 5.5

2. No errors on build.

**Desktop (please complete the following information):**
- OS Type & Version: Linux x64 (Ubuntu 19.10)
- Java/JDK version: AdoptOpenJDK 11.0.4+11
- IntelliJ IDEA version: N/A (just using Gradle in its raw state)
- Gradle: 5.5.1 or later
- Manifold version: 2019.1.11 (also tested 2019.1.10 on manifold-all)
- Manifold IntelliJ plugin version: N/A

**Stack trace**

```
./gradlew clean jar                     

> Task :compileJava FAILED
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.4, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.RuntimeException: java.lang.RuntimeException: Method 'getLocationAsPaths' not found
        at manifold.internal.javac.JavacFileManagerBridge.getLocationAsPaths(JavacFileManagerBridge.java:136)
        at manifold.internal.javac.JavacFileManagerBridge.hasLocation(JavacFileManagerBridge.java:106)
        at manifold.internal.javac.ManifoldJavaFileManager.hasLocation(ManifoldJavaFileManager.java:106)
        at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.getModuleInfoFromLocation(ModuleFinder.java:279)
        at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findSingleModule(ModuleFinder.java:200)
        at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:453)
        at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:267)
        at jdk.compiler/com.sun.tools.javac.comp.Modules.initModules(Modules.java:233)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initModules(JavaCompiler.java:1045)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:939)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:93)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:99)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:79)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:44)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:34)
        at org.gradle.workers.internal.FlatClassLoaderWorker.execute(FlatClassLoaderWorker.java:33)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:116)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Method 'getLocationAsPaths' not found
        at manifold.util.ReflectUtil.method(ReflectUtil.java:160)
        at manifold.internal.javac.JavacFileManagerBridge.getLocationAsPaths(JavacFileManagerBridge.java:132)
        ... 43 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed

```

**Comment by rsmckinney** [comment]
Please retry with version '2019.1.12'

Thanks!

**Comment by StrangeNoises** [comment]
Confirmed. Successful build (albeit with no actual use of the features therein yet) on project with gradle 5.6.
