### ISSUE TITLE
idea plugin error

### ISSUE THREAD

**Issue by wxq1990** [manifold-systems/manifold#117]
**Describe the bug**
have error when build my project in idea

**Screenshots**
![_$ I$9SYC89N@UH~2JQ}64T](https://user-images.githubusercontent.com/10300594/63842416-14ff8900-c9b7-11e9-9bd8-b05976f15459.png)

**Desktop (please complete the following information):**
- OS Type & Version:  win10
- Java/JDK version: java11
- IntelliJ IDEA version: 2019.2.1 Cummunity
- Manifold version: 2019.1.12
- Manifold IntelliJ plugin version:  2019.1.12
-gradlew:5.6.1

**Stack trace**

``java.nio.file.NoSuchFileException: D:\Users\west.w\.gradle\caches\modules-2\files-2.1\systems.manifold\manifold-all\2019.1.12\4867475d1a73d8eb1e9fd5a4faae26951bf79463\manifold-all-2019.1.12.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:194)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1222)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
	at manifold.ij.core.ManLibraryChecker.getManifoldJars(ManLibraryChecker.java:260)
	at manifold.ij.core.ManLibraryChecker.getManifoldJarsInProject(ManLibraryChecker.java:234)
	at manifold.ij.core.ManLibraryChecker.getVersionFromProject(ManLibraryChecker.java:161)
	at manifold.ij.core.ManLibraryChecker.isUsingManifoldJars(ManLibraryChecker.java:96)
	at manifold.ij.core.ManProject.init(ManProject.java:204)
	at manifold.ij.core.ManProject.lambda$reset$4(ManProject.java:282)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:902)
	at manifold.ij.core.ManProject.reset(ManProject.java:278)
	at manifold.ij.extensions.ModuleClasspathListener.resetProject(ModuleClasspathListener.java:33)
	at manifold.ij.extensions.ModuleClasspathListener.rootsChanged(ModuleClasspathListener.java:23)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:102)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:446)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:370)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:242)
	at com.sun.proxy.$Proxy49.modificationCountChanged(Unknown Source)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:75)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.incCountersInner(PsiModificationTrackerImpl.java:82)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:99)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:344)
	at com.intellij.psi.impl.PsiManagerImpl.propertyChanged(PsiManagerImpl.java:318)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$MyModuleRootListener.lambda$rootsChanged$2(PsiVFSListener.java:595)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$MyModuleRootListener.rootsChanged(PsiVFSListener.java:585)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:102)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:446)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:370)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:242)
	at com.sun.proxy.$Proxy107.rustStructureChanged(Unknown Source)
	at org.rust.lang.core.psi.RsPsiManagerImpl.incRustStructureModificationCount(RsPsiManager.kt:153)
	at org.rust.lang.core.psi.RsPsiManagerImpl.incRustStructureModificationCount(RsPsiManager.kt:149)
	at org.rust.lang.core.psi.RsPsiManagerImpl$projectOpened$1.rootsChanged(RsPsiManager.kt:67)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:102)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:446)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:242)
	at com.sun.proxy.$Proxy105.rootsChanged(Unknown Source)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.fireRootsChangedEvent(ProjectRootManagerComponent.java:179)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:391)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$200(ProjectRootManagerImpl.java:34)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:92)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:302)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.commit(AbstractIdeModifiableModelsProvider.java:315)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl$3.execute(ProjectDataManagerImpl.java:436)
	at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:22)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.lambda$executeProjectChangeAction$4(ExternalSystemApiUtil.java:355)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:152)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wxq1990** [comment]
Hi @rsmckinney.  after clean all gradle cache,still have this error when build project . Manifold did not recover .

**Comment by rsmckinney** [comment]
@wxq1990, I can help diagnose the problem with access to your project. In any case the exception doesn’t make sense if the file exists at that location, and if it doesn’t exist, IJ is providing an invalid library path which is also strange, so I suspect it’s something specific to your environment. Debugging IJ would likely expose the root cause.

**Comment by wxq1990** [comment]
thanks ,i will fix it  myself

**Comment by wxq1990** [comment]
thanks ,i will fix it  myself

**Comment by wxq1990** [comment]
thanks ,i will fix it  myself

**Comment by wxq1990** [comment]
i found it probably because jdk not Incompatible with plugin  ,when using openjdk11(build 11+28) ,error occurs. however it work nomally when use idea' bundle jbr(11.0.3)

**Comment by rsmckinney** [comment]
Hi @wxq1990.  Can you try with the latest plugin update (2019.1.14)?  Latest Java 11 OpenJDK (11.04+11) works for us.

**Comment by wxq1990** [comment]
now there is another error  ,code assist do not work. e.g. check exception still exists, extension method not found. it seems like plugin do not work.

**Comment by wxq1990** [comment]
![JO13~MM1OJ({ ~ PJ)PO9WK](https://user-images.githubusercontent.com/10300594/64506164-1d39bb80-d309-11e9-9900-e9f8b9627227.png)
when id delete the directory 'jdr',error occurs,otherwise plugin works normal
