### ISSUE TITLE
run error use jre

### ISSUE THREAD

**Issue by wxq1990** [manifold-systems/manifold#184]
**Describe the bug**
run normal use jdk11 .run error use jre11

**To Reproduce**
run use jre11

**Expected behavior**
**Screenshots**
![QQ图片20200520181654](https://user-images.githubusercontent.com/10300594/82434950-31ec6700-9ac6-11ea-887d-8021ab21a3b9.png)

**Desktop (please complete the following information):**
- OS Type & Version: win 10
- Java/JRE version: 11
- IntelliJ IDEA version: 2020.1
- Manifold version: 2020.1.9
- Manifold IntelliJ plugin version: 2020.1.9

**Additional context**

**Stack trace**
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: Error initializing Manifold
        at manifold.util.NecessaryEvilUtil.openJavaBase(NecessaryEvilUtil.java:176)
        at manifold.util.NecessaryEvilUtil.bypassJava9Security(NecessaryEvilUtil.java:78)
        at manifold.api.host.IRuntimeManifoldHost.preBootstrap(IRuntimeManifoldHost.java:40)
        at manifold.internal.host.RuntimeManifoldHost.bootstrap(RuntimeManifoldHost.java:115)
        at manifold.internal.host.RuntimeManifoldHost.bootstrap(RuntimeManifoldHost.java:99)
        at manifold.internal.runtime.Bootstrap.init(Bootstrap.java:220)
        at com.pax.palis.Application.<clinit>(Application.java:23)
        ... 8 more
Caused by: java.lang.NullPointerException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at manifold.util.ReflectUtil$MethodRef.invoke(ReflectUtil.java:595)
        at manifold.util.NecessaryEvilUtil.openJavaBase(NecessaryEvilUtil.java:140)
        ... 14 more

**Comment by rsmckinney** [comment]
@wxq1990 With Java 11 there is no a JDK/JRE divide as there was with Java 8.  Java 11 only has an SDK, so I'm a bit confused as to what you're using for your "JRE".  Please clarify.  Thanks!

**Comment by wxq1990** [comment]
i deploy my project with docker,to reduce memory consumption, I use  base image"openjdk:11.0.7-jre-slim"

**Comment by rsmckinney** [comment]
@wxq1990 Perhaps use the full openjdk image, not the "slim" one?  Note, if you are concerned about jdk size, you can use jlink to tailor a runtime specifically for you app.

**Comment by wxq1990** [comment]
ok
