### ISSUE TITLE
Read access exception

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#212]
Issue reported via email:

Just installed the plugin in the latest version of IntelliJ and this happened after I started using the library.
Details: Current thread: Thread[Alarm Pool,4,Idea Thread Group] 1707850939
; dispatch thread: false; isDispatchThread(): false

SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 2028404036
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
                at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
                at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1013)
                at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:591)
                at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:587)
                at com.intellij.psi.impl.source.PsiFileImpl.isValid(PsiFileImpl.java:162)
                at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:299)
                at manifold.ij.extensions.ManPreprocessorAnnotator.doAnnotate(ManPreprocessorAnnotator.java:71)
                at manifold.ij.extensions.ManPreprocessorAnnotator.doAnnotate(ManPreprocessorAnnotator.java:31)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:205)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$800(ExternalToolPass.java:41)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:181)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:271)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:41)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:181)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
                at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
                at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
                at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
                at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
                at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
                at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
                at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
                at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
                at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
                at com.intellij.util.Alarm$Request.run(Alarm.java:356)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
                at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
                at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
                at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
                at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
                at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
                at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by rsmckinney** [comment]
Fixed with change https://github.com/manifold-systems/manifold-ij/commit/603547fe961fbaf8767d1ab3d88ced9a8898a5cb 
Available in coming IJ plugin release.
