### ISSUE TITLE
Cannot build with the IJ plugin starting with IJ v2020.1+ with JBR 11 if using a Java 8 project

### ISSUE THREAD

**Issue by rsmckinney** [manifold-systems/manifold#224]
**Describe the bug**
Cannot build with the IJ plugin starting with IJ v2020.1+ with JBR 11 if using a Java 8 project

**To Reproduce**
1. Using IJ 2020.2 JBR 11 with Manifold plugin 2020.2, create a Java project using JDK 8
2. Rebuild
3. Stack trace:
>java.lang.UnsupportedClassVersionError: manifold/ij/jps/ManBuildService has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.intellij.util.containers.ContainerUtilRt.copy(ContainerUtilRt.java:113)
	at com.intellij.util.containers.ContainerUtil.newArrayList(ContainerUtil.java:206)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl$SingleClassLoaderPluginManager.loadExtensions(JpsServiceManagerImpl.java:120)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:112)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:60)
	at org.jetbrains.jps.incremental.TargetTypeRegistry.<init>(TargetTypeRegistry.java:25)
	at org.jetbrains.jps.incremental.TargetTypeRegistry.<init>(TargetTypeRegistry.java:13)
	at org.jetbrains.jps.incremental.TargetTypeRegistry$Holder.<clinit>(TargetTypeRegistry.java:16)
	at org.jetbrains.jps.incremental.TargetTypeRegistry.getInstance(TargetTypeRegistry.java:21)
	at org.jetbrains.jps.builders.impl.BuildTargetRegistryImpl.<init>(BuildTargetRegistryImpl.java:41)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:76)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:271)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:127)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rsmckinney** [comment]
fixed with IJ plugin releases 2020.3.32, 2020.1.32, 2019.3.32

**Comment by schittli** [comment]
Thanks a lot!, this issue is gone :-)
