### ISSUE TITLE
Error when compiling in IntelliJ 

### ISSUE THREAD

**Issue by dlilljegren** [manifold-systems/manifold#23]
After upgrading IntelliJ and maybe also the Manifold plugin, I started to get these

Seems to go away ( sometimes ) if I clean the IntelliJ cache

_Error:java: Fatal error processing with Manifold type processor: manifold.ext.ExtensionManifold
  on type: _temp_._Manifold_Temp_Main_2
  Please report the error with the accompanying stack trace.
  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  	at manifold.util.ReflectUtil$MethodRef.invokeStatic(ReflectUtil.java:346)
  	at manifold.ext.ExtensionTransformer.getIncrementalCompileDrivers(ExtensionTransformer.java:410)
  	at manifold.ext.ExtensionTransformer.findDrivers(ExtensionTransformer.java:378)
  	at manifold.ext.ExtensionTransformer.incrementalCompileClasses(ExtensionTransformer.java:362)
  	at manifold.ext.ExtensionTransformer.visitClassDef(ExtensionTransformer.java:277)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
  	at manifold.ext.ExtensionManifold.process(ExtensionManifold.java:241)
  	at manifold.internal.javac.TypeProcessor.process(TypeProcessor.java:97)
  	at manifold.internal.javac.CompiledTypeProcessor.finished(CompiledTypeProcessor.java:256)
  	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1410)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1367)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:965)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:193)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:448)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:318)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:243)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:201)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1317)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:993)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1065)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:956)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:788)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:377)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:184)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:309)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:137)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:844)
  Caused by: java.lang.reflect.InvocationTargetException
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  	at manifold.util.ReflectUtil$MethodRef.invokeStatic(ReflectUtil.java:342)
  	... 39 more
  Caused by: java.lang.IllegalStateException
  	at manifold.ij.jps.IjIncrementalCompileDriver.getInstance(IjIncrementalCompileDriver.java:26)
  	... 44 more_

**Comment by rsmckinney** [comment]
Hi.

As a quick remedy you can delete any stale `temp.Manifold_Temp_Main_*.java` files manifold may have left in your project.  There was a bug in an older version of Manifold that didn't clean build artifacts as it should have.  This is fixed in the current version of the plugin.

In any case, please provide the following info from your environment:

- IntelliJ Version
- Manifold Version
- Java Version in your project
- If Java 11, are you using module-info.java files?
- Are you using a build tool such as maven or gradle?
- Your project would also help, if you could include a link to it or simply drag and drop a compressed version of it directly into a github issue message like this one.

This info will help me diagnose the issue further. 

Thanks for reporting this issue!

**Comment by dlilljegren** [comment]
Hi,

**IntelliJ Version**
IntelliJ IDEA 2018.2.5 (Community Edition)
Build #IC-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Manifold Version**
Version: 0.25.2-alpha

**Java**
10.0.2

**If Java 11, are you using module-info.java files?**
No

**Are you using a build tool such as maven or gradle?**
It's a Maven Project
 <dependency>
            <groupId>systems.manifold</groupId>
            <artifactId>manifold-all</artifactId>
            <version>${manifold-version}</version>
        </dependency>
 <manifold-version>RELEASE</manifold-version>
 <compilerArgs>      
                        <arg>-Xplugin:Manifold strings</arg>
  </compilerArgs>

**Project Zip**
[akkatest.zip](https://github.com/manifold-systems/manifold/files/2533660/akkatest.zip)


Thanks, for me, getting extension methods in Java is really useful

**Comment by rsmckinney** [comment]
This is now fixed in latest, but won't be available on the IJ plugin repo for a few days.

The information you posted helped a lot, Thanks!
