### ISSUE TITLE
Manifold Properties don't compile with JDK 16

### ISSUE THREAD

**Issue by AleMuzzi** [manifold-systems/manifold#255]
**Describe the bug**
I am trying to compile my project on IntelliJ IDEA with maven, I'm using JDK 16 and everything goes fine till I added manifold properties dependency

```
<dependency>
    <groupId>systems.manifold</groupId>
    <artifactId>manifold-props-rt</artifactId>
    <version>${manifold.version}</version>
</dependency>
```
and related plugin path.

The error is the following:
```
java.lang.NoSuchMethodError: 'boolean com.sun.tools.javac.code.Symbol.isLocal()'
        at manifold.ext.props.Util.isPropertyField(Util.java:160)
        at manifold.ext.props.PropertyInference.handleExistingField(PropertyInference.java:419)
        at manifold.ext.props.PropertyInference.makeVal(PropertyInference.java:274)
        at manifold.ext.props.PropertyInference.handleVals(PropertyInference.java:217)
        at manifold.ext.props.PropertyInference.inferProperties(PropertyInference.java:74)
        at manifold.ext.props.PropertyProcessor.inferPropertiesFromClassReader(PropertyProcessor.java:156)
        at manifold.ext.props.ClassReaderCompleter.lambda$complete$1(ClassReaderCompleter.java:132)
        at jdk.compiler/com.sun.tools.javac.comp.Annotate.flush(Annotate.java:191)
        at jdk.compiler/com.sun.tools.javac.comp.Annotate.unblockAnnotations(Annotate.java:144)
        at jdk.compiler/com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:157)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterDone(JavaCompiler.java:1750)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1071)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**To Reproduce**
1. Create a new maven project
2. Add manifold properties plugin dependency
3. Add a class with at least a @var
4. Compile, you will get a generic error (execute `mvn clean install -X` to see error details ) 

**Expected behavior**
Compile of @var fields is performed correctly.

**Desktop (please complete the following information):**
- OS Type & Version:  macOS Catalina
- Java/JDK version: JDK 16 (X)
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2020.3.2, here some informations about it:
```
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to Alessandro Muzzi
Subscription is active until December 28, 2021.
For educational use only.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: actionSystem.force.alt.gr=true
Non-Bundled Plugins: manifold.ij, Dart, org.jetbrains.kotlin
```
- Manifold version: 2021.1.9
- Manifold IntelliJ plugin version: 2020.3.39

**Stack trace**
Already applied in description.

**Comment by AleMuzzi** [comment]
If you want you can directly try it on my project: [https://bitbucket.org/alessandromuzzi17/assegnamento1/src/v3/](https://bitbucket.org/alessandromuzzi17/assegnamento1/src/v3/)

**Comment by rsmckinney** [comment]
Hi @AleMuzzi.  There are a couple of issues I'm working on related to JDK 16 and manifold-props. I expect to have this fixed in the next few days. In the meantime you can use jdk 15 or older with manifold-props, if that works for you.  Apologies for the problem.

**Comment by AleMuzzi** [comment]
Hi, thanks for the fast response. I have downgraded the project to JDK 15 but it can't compile anyway. If I let IntelliJ manage the building it gives me errors like `java: illegal reference to restricted type 'var'`.
It gives me this error even if I go under **Preferences -> Build, Execution, Deployment -> Build Tools -> Maven -> Runner** and I check the entry "Delegate IDE build/run to Maven"

**Comment by AleMuzzi** [comment]
While there are no error for the IDE, for IntelliJ @var are correctly accessible

**Comment by AleMuzzi** [comment]
Compiling with JDK 11 also gives me errors, in particular `java: obj has private access in it.muzzialessandro.model.Request` .
I really can't understand if there's something wrong with my code/project settings or what

**Comment by rsmckinney** [comment]
Your pom.xml is missing the `-Xplugin:Manifold` compiler argument:
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>16</source>
                    <target>16</target>
                    <encoding>UTF-8</encoding>
                    <compilerArgs>
                        <!-- Configure manifold plugin -->
                        <arg>-Xplugin:Manifold</arg>
                    </compilerArgs>
                    <!-- Add the processor path for the plugin -->
                    <annotationProcessorPaths>
  . . . 
```
Note, you can find setup information for any of the Manifold features online in the README.md files. For instance, the [`manifold-props` Maven setup](https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-props#setup).

Note, the fix for Java 16 is testing and will be released soon.

**Comment by AleMuzzi** [comment]
You are totally right, must have deleted it by error playing with the pom.xml. Anyway I still get this error, even with JDK 15. I have just updated the repo.

> Compiling with JDK 11 also gives me errors, in particular `java: obj has private access in it.muzzialessandro.model.Request` when `obj` is a property (`@var`) of the `Request` class .
> I really can't understand if there's something wrong with my code/project settings or what

**Comment by rsmckinney** [comment]
Ah, I've found the issue.  There is an internal bug in manifold-props where an the property type is not referenced correctly if it is an inner class/enum.  Basically, if you change the two inner enum classes you have to top-level enum classes, your build works.  Following is a clipboard patch you can apply in IntelliJ.  This will be fixed in the next release coming in the next 24 hours. 

Thanks for reporting this! The manifold-props features is brand new and still in the "experimental" phase. Early reports like yours help tremendously.

Clipboard patch:
```
Index: src/main/java/it/muzzialessandro/ServerThread.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/ServerThread.java b/src/main/java/it/muzzialessandro/ServerThread.java
--- a/src/main/java/it/muzzialessandro/ServerThread.java	(revision cea2ceb039428f55b26aafc344f225be27e31936)
+++ b/src/main/java/it/muzzialessandro/ServerThread.java	(date 1616788748623)
@@ -3,7 +3,7 @@
 import it.muzzialessandro.manager.ErrorManager;
 import it.muzzialessandro.model.records.ClientModel;
 import it.muzzialessandro.model.Request;
-import it.muzzialessandro.model.Request.RequestCode;
+import it.muzzialessandro.model.RequestCode;
 import it.muzzialessandro.manager.PacketManager;
 
 import java.io.*;
Index: src/main/java/it/muzzialessandro/ClientNode.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/ClientNode.java b/src/main/java/it/muzzialessandro/ClientNode.java
--- a/src/main/java/it/muzzialessandro/ClientNode.java	(revision cea2ceb039428f55b26aafc344f225be27e31936)
+++ b/src/main/java/it/muzzialessandro/ClientNode.java	(date 1616788822733)
@@ -1,12 +1,9 @@
 package it.muzzialessandro;
 
 import it.muzzialessandro.manager.ErrorManager;
-import it.muzzialessandro.model.NetworkClient;
+import it.muzzialessandro.model.*;
 import it.muzzialessandro.model.records.ClientModel;
-import it.muzzialessandro.model.Request;
-import it.muzzialessandro.model.Request.RequestCode;
-import it.muzzialessandro.model.Response;
-import it.muzzialessandro.model.Response.ResponseCode;
+import it.muzzialessandro.model.ResponseCode;
 import it.muzzialessandro.manager.ConfigurationManager;
 import it.muzzialessandro.manager.PacketManager;
 import it.muzzialessandro.utils.ClosableLinkedBlockingQueue;
Index: src/main/java/it/muzzialessandro/model/Response.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/model/Response.java b/src/main/java/it/muzzialessandro/model/Response.java
--- a/src/main/java/it/muzzialessandro/model/Response.java	(revision cea2ceb039428f55b26aafc344f225be27e31936)
+++ b/src/main/java/it/muzzialessandro/model/Response.java	(date 1616788974100)
@@ -9,10 +9,6 @@
  * The class {@code Response} provides a simplified model of a response message.
  **/
 public class Response implements Serializable {
-    public enum ResponseCode {
-        OK,
-        ERROR
-    }
 
     @Serial
     private static final long serialVersionUID = 1L;
Index: src/main/java/it/muzzialessandro/model/Request.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/model/Request.java b/src/main/java/it/muzzialessandro/model/Request.java
--- a/src/main/java/it/muzzialessandro/model/Request.java	(revision cea2ceb039428f55b26aafc344f225be27e31936)
+++ b/src/main/java/it/muzzialessandro/model/Request.java	(date 1616788974106)
@@ -12,13 +12,6 @@
  * The class {@code Request} provides a simplified model of a request message.
  **/
 public class Request implements Serializable {
-    public enum RequestCode {
-        REGISTRATION,
-        NETWORK_INFO,
-        RESEND_MESSAGE,
-        MESSAGE_TRANSMISSION_END,
-        STATISTICS
-    }
 
     @Serial
     private static final long serialVersionUID = 1L;
Index: src/main/java/it/muzzialessandro/model/RequestCode.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/model/RequestCode.java b/src/main/java/it/muzzialessandro/model/RequestCode.java
new file mode 100644
--- /dev/null	(date 1616788748611)
+++ b/src/main/java/it/muzzialessandro/model/RequestCode.java	(date 1616788748611)
@@ -0,0 +1,9 @@
+package it.muzzialessandro.model;
+
+public enum RequestCode {
+    REGISTRATION,
+    NETWORK_INFO,
+    RESEND_MESSAGE,
+    MESSAGE_TRANSMISSION_END,
+    STATISTICS
+}
Index: src/main/java/it/muzzialessandro/manager/PacketManager.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/manager/PacketManager.java b/src/main/java/it/muzzialessandro/manager/PacketManager.java
--- a/src/main/java/it/muzzialessandro/manager/PacketManager.java	(revision cea2ceb039428f55b26aafc344f225be27e31936)
+++ b/src/main/java/it/muzzialessandro/manager/PacketManager.java	(date 1616788822751)
@@ -1,7 +1,9 @@
 package it.muzzialessandro.manager;
 
 import it.muzzialessandro.model.Request;
+import it.muzzialessandro.model.RequestCode;
 import it.muzzialessandro.model.Response;
+import it.muzzialessandro.model.ResponseCode;
 import it.muzzialessandro.model.records.MessageModel;
 
 import java.io.IOException;
@@ -16,10 +18,10 @@
         PacketManager.sendOkResponse(os, "");
     }
     public static void sendOkResponse(ObjectOutputStream os, String msg) {
-        PacketManager.sendPacket(os, new Response(Response.ResponseCode.OK, msg));
+        PacketManager.sendPacket(os, new Response(ResponseCode.OK, msg));
     }
     public static void sendOkResponse(ObjectOutputStream os, Serializable payload) {
-        PacketManager.sendPacket(os, new Response(Response.ResponseCode.OK, payload));
+        PacketManager.sendPacket(os, new Response(ResponseCode.OK, payload));
     }
 
     public static void sendErrorResponse(ObjectOutputStream os) {
@@ -27,18 +29,18 @@
     }
 
     public static void sendErrorResponse(ObjectOutputStream os, String msg) {
-        PacketManager.sendPacket(os, new Response(Response.ResponseCode.ERROR, msg));
+        PacketManager.sendPacket(os, new Response(ResponseCode.ERROR, msg));
     }
 
     public static void sendErrorResponse(ObjectOutputStream os, Serializable payload) {
-        PacketManager.sendPacket(os, new Response(Response.ResponseCode.ERROR, payload));
+        PacketManager.sendPacket(os, new Response(ResponseCode.ERROR, payload));
     }
 
-    public static void sendRequest(ObjectOutputStream os, Request.RequestCode code) {
+    public static void sendRequest(ObjectOutputStream os, RequestCode code) {
         PacketManager.sendRequest(os, code, null);
     }
 
-    public static void sendRequest(ObjectOutputStream os, Request.RequestCode code, Serializable obj) {
+    public static void sendRequest(ObjectOutputStream os, RequestCode code, Serializable obj) {
         PacketManager.sendPacket(os, new Request(code, obj));
     }
 
Index: src/main/java/it/muzzialessandro/model/ResponseCode.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/model/ResponseCode.java b/src/main/java/it/muzzialessandro/model/ResponseCode.java
new file mode 100644
--- /dev/null	(date 1616788822715)
+++ b/src/main/java/it/muzzialessandro/model/ResponseCode.java	(date 1616788822715)
@@ -0,0 +1,6 @@
+package it.muzzialessandro.model;
+
+public enum ResponseCode {
+    OK,
+    ERROR
+}
Index: src/main/java/it/muzzialessandro/ClientSendThread.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/it/muzzialessandro/ClientSendThread.java b/src/main/java/it/muzzialessandro/ClientSendThread.java
--- a/src/main/java/it/muzzialessandro/ClientSendThread.java	(revision cea2ceb039428f55b26aafc344f225be27e31936)
+++ b/src/main/java/it/muzzialessandro/ClientSendThread.java	(date 1616788748586)
@@ -3,7 +3,7 @@
 import it.muzzialessandro.manager.ErrorManager;
 import it.muzzialessandro.manager.PacketManager;
 import it.muzzialessandro.model.NetworkClient;
-import it.muzzialessandro.model.Request;
+import it.muzzialessandro.model.RequestCode;
 import it.muzzialessandro.model.records.MessageModel;
 
 import java.io.*;
@@ -80,7 +80,7 @@
                 System.out.println("All packets sent, theoretically.");
 
                 // now all messages have been theoretically sent, let's check if it's all ok
-                PacketManager.sendRequest(netClientOS, Request.RequestCode.MESSAGE_TRANSMISSION_END, this.clientNode.clientModel.id);
+                PacketManager.sendRequest(netClientOS, RequestCode.MESSAGE_TRANSMISSION_END, this.clientNode.clientModel.id);
                 // wait for updates from receive thread
                 this.netClient.wait();
 
```

**Comment by rsmckinney** [comment]
@AleMuzzi I've found a fixed the issues related to what you've reported there (JDK 16 related and also an issue with inner enum/classes).  Your project now successfully builds with JDK 16.  Thank you for reporting this issue, it makes all the difference during this "experimental" stage of `manifold-props`.

Please use release `2021.1.10`.

**Comment by AleMuzzi** [comment]
I'm really glad to hear that! I've just tested the new version with JDK 16 and it works like a charm. The only thing I noticed is that just changing the plugin version in pom.xml led to a build success but the IDE still kept reporting error in files containing `@var`. After I have performed an uninstall and a reinstall of the plugin everything worked fine. Thanks for the fast fix! I'm glad I have helped you, you're doing an awesome job, this plugin is a game changing in Java programming.

**Comment by rsmckinney** [comment]
Regarding the reinstall, sometimes Intellij requires a manual refresh from Maven/Gradle after a build change:

<p><img src="https://user-images.githubusercontent.com/588843/112725809-444de300-8ed7-11eb-991e-e84dccc63cf0.png" alt="manifold ij plugin" width="40%" height="40%"/></p>

**Comment by AleMuzzi** [comment]
Oh, ok, I'll keep it in mind, thanks.
