### ISSUE TITLE
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.11, {1}, {2}, {3}, {4}, {5}, {6}, {7}

### ISSUE THREAD

**Issue by XiaoPangxie732** [manifold-systems/manifold#264]
**Describe the bug**
See https://github.com/PistonMinecraft/Piston-PluginAPI/runs/2432121082?check_suite_focus=true

**To Reproduce**
1.Run gradlew build in the project in the description above

**Expected behavior**
Compile successfully

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version: ubuntu-latest on GitHub Actions. Windows 10 x64 on my personal computer(both failed)
- Java/JDK version: JDK 11.0.11
- IDE version (IntelliJ IDEA or Android Studio): 2021.1
- Manifold version: 2021.1.11
- Manifold IntelliJ plugin version: 2021.1.10

**Additional context**

**Stack trace**
Please include a stack trace if applicable

**Comment by rsmckinney** [comment]
@XiaoPangxie732 Hi.  I get the following error when I open your project:

Could not resolve all artifacts for configuration 'incomingCatalogForLibs0'.
> Could not resolve org.pistonmc.api:api-common-catalog:0.1.0.+.
  Required by:
      unspecified:unspecified:unspecified
   > Failed to list versions for org.pistonmc.api:api-common-catalog.
      > Unable to load Maven meta-data from https://maven.pkg.github.com/PistonMinecraft/PistonAPI-Common/org/pistonmc/api/api-common-catalog/maven-metadata.xml.
         > Could not get resource 'https://maven.pkg.github.com/PistonMinecraft/PistonAPI-Common/org/pistonmc/api/api-common-catalog/maven-metadata.xml'.
            > Username must not be null!

**Comment by XiaoPangxie732** [comment]
@rsmckinney I use GitHub Packages to deploy the dependencies. So you need a GitHub personal access token with `read:packages` permission at least. Then you need to create an environment variable named `GPR_USERNAME` with your GitHub username, then create an environment variable named `GPR_TOKEN` with the token. After that, restart the IDE or terminal. Then it should work.

**Comment by XiaoPangxie732** [comment]
So... what's the solution?

**Comment by rsmckinney** [comment]
Hi @XiaoPangxie732, apologies for the delay.  I'll look at this over the weekend.

**Comment by rsmckinney** [comment]
Still haven't configured for github packages, however looking more closely at the stack trace you provided the core problem is most likely a configuration error wrt lombok and your use of @AllArgsConstructor in NamespaceResource:

```
/home/runner/work/Piston-PluginAPI/Piston-PluginAPI/src/main/java/org/pistonmc/api/plugin/NamespacedResource.java:11: error: cannot find symbol
@AllArgsConstructor(onConstructor_ = @NonNull)
                    ^
  symbol:   method onConstructor_()
  location: @interface AllArgsConstructor
```

I'm not a lombok user, but for this to work lombok would have to hack the java AST during annotation processing to get that to work. So I would say lombok is somehow not engaged at the time this is compiled, which implies a configuration error.  Could it be that the way you have configured manifold using github stuff is not compatible with the lombok plugin you are using?

**Comment by XiaoPangxie732** [comment]
Here is Lombok's doc:
```
Any annotations listed here are put on the generated constructor. The syntax for this feature depends on JDK version (nothing we can do about that; it's to work around javac bugs).
up to JDK7: @AllArgsConstructor(onConstructor=@__({@AnnotationsGoHere}))
from JDK8: @AllArgsConstructor(onConstructor_={@AnnotationsGohere}) // note the underscore after onConstructor.
Returns: List of annotations to apply to the generated constructor.
```

So this isn't a Lombok error. Though I delete `onConstructor_ = @NonNull`, the error still produces.

**Comment by rsmckinney** [comment]
Right.  It appears the lombok annotation processor is not loaded/working, so I'm suggesting it is a _configuration_ error perhaps related to how your project depends on manifold.

**Comment by XiaoPangxie732** [comment]
So what should I do? I removed Lombok, but the error still produces.

**Comment by XiaoPangxie732** [comment]
> so I'm suggesting it is a _configuration_ error perhaps related to how your project depends on manifold.

What does it mean? What should I do?

**Comment by rsmckinney** [comment]
Make an alternative build configuration where you don't use github packages for manifold, instead use normal dependencies.  Unfortunately, this week is quite full for me, but I will try to find some time to try this myself with your project.

**Comment by XiaoPangxie732** [comment]
https://github.com/PistonMinecraft/Piston-PluginAPI
I pushed commits. Now it doesn't use the dependencies deployed on GitHub Packages anymore.

By the way, I ran the build on Java 16. It outputs a more detailed error message:
<summary>
<details>

```
java.lang.NullPointerException: Cannot invoke "java.util.Queue.iterator()" because the return value of "com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()" is null
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.unrecoverableError(JavaCompiler.java:1280)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.shouldStop(JavaCompiler.java:577)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1392)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1378)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.gradle.internal.compiler.java.IncrementalCompileTask.call(IncrementalCompileTask.java:77)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:94)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:55)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:40)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
        at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
        at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

</details>
</summary>
Hope it helps :)

**Comment by XiaoPangxie732** [comment]
I think this is caused by manifold-props. I will test later to see if my idea is correct.

**Comment by XiaoPangxie732** [comment]
Currently, I found that the following will cause an error:
```java
public interface Itf {
  String m();
  @val String s = m();
}
```
The problem is that you can't invoke methods/get properties in the interface from a val property initializer in the interface.

**Comment by XiaoPangxie732** [comment]
@rsmckinney Hi. I found out why this error would produce. See the bug above.

**Comment by XiaoPangxie732** [comment]
@rsmckinney Hi. I found out why this error produced. It's because of the bug above.

**Comment by XiaoPangxie732** [comment]
`compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.11, {1}, {2}, {3}, {4}, {5}, {6}, {7}`
And this error is produced when you apply an annotation that cannot apply to a method(no `ElementType.METHOD`) to a setter through `@var`
I think this is also a bug. Because apply an annotation that cannot apply to a method to a method should print a specific error message instead of just `compiler message file broken`
And currently, I found that only Gradle causes this `compiler message file broken`

**Comment by rsmckinney** [comment]
Fixed a while back.  Compile error is now:

> non-static method m() cannot be referenced from a static context
