### ISSUE TITLE
Intellij unable to build java project with manifold-preprocessor

### ISSUE THREAD

**Issue by ahmed6262445** [manifold-systems/manifold#369]
When building application using manifold preprocessor through intellij it gives out null reference, consequently if you compile the application using "mvn compile" it compiles fine. Due to which unable to debug the application

**To Reproduce**
1. Create simple java maven project (e.g maven-archetype-quickstart)
2. Modify pom.xml using the following link https://github.com/manifold-systems/manifold/tree/master/manifold-deps-parent/manifold-preprocessor#Maven
3. Now build application from intellij

**Desktop**
- OS Type & Version: Windows 10
- Java/JDK version: 11.0.11
- IDE version (IntelliJ IDEA): 2021.2.1 (CE)
- Manifold version: 2022.1.14
- Manifold IntelliJ plugin version: 2021.2.48

**Stack trace**
```
java: Internal error: 
java.lang.NullPointerException
	at manifold.util.concurrent.ConcurrentWeakHashMap.get(ConcurrentWeakHashMap.java:1009)
	at manifold.util.ReflectUtil.getRawMethodFromCache(ReflectUtil.java:1149)
	at manifold.util.ReflectUtil.getMethodFromCache(ReflectUtil.java:1139)
	at manifold.util.ReflectUtil._method(ReflectUtil.java:325)
	at manifold.util.ReflectUtil.method(ReflectUtil.java:315)
	at manifold.util.ReflectUtil.method(ReflectUtil.java:298)
	at manifold.internal.javac.JavacPlugin.overrideJavacToolEnter(JavacPlugin.java:203)
	at manifold.internal.javac.JavacPlugin.init(JavacPlugin.java:195)
	at manifold.internal.javac.JavacPluginBootstrap.init(JavacPluginBootstrap.java:49)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:215)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:199)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:238)
	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:514)
	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:560)
	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:512)
	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:355)
	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:280)
	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:234)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1485)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1123)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1268)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1088)
	at org.jetbrains.jps.incremental.IncProjectBuilder.access$1200(IncProjectBuilder.java:69)
	at org.jetbrains.jps.incremental.IncProjectBuilder$BuildParallelizer$1.run(IncProjectBuilder.java:1028)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
```

**Comment by ahmed6262445** [comment]
@rsmckinney thank you for replying. As far as Java 11 JDK is concerned, project is referencing JDK 11.

![image](https://user-images.githubusercontent.com/57043614/171334046-22d47119-b7a5-4e8b-a8fe-56150a6e5c22.png)

![image](https://user-images.githubusercontent.com/57043614/171334085-58e3a1ad-936c-4fb0-b732-db7afdad8822.png)

**Comment by ahmed6262445** [comment]
The issue still persists, the main issue is that I am unable to build or debug from native settings used for running java application in intellij.
After executing the steps you mentioned following is the output (application compiles and debugger exits):
![image](https://user-images.githubusercontent.com/57043614/171381509-04237915-2c10-43e7-86c9-c3957bbfcec6.png)
![image](https://user-images.githubusercontent.com/57043614/171381562-63a2d675-ecd9-415b-b7d5-91b5e3944f90.png)

**Comment by ahmed6262445** [comment]
@rsmckinney any update sir?
Error still persists.

**Comment by ahmed6262445** [comment]
@rsmckinney thank you will try to run sample project provided by you.

**Comment by dont-doubt** [comment]
The issue gets thrown when running Gradle with JDK 9+ onto the project with set JDK 8. Probably causes by wrong `JreUtil`'s Java version determination through `java.version` property

Wrote steps to reproduce to @rsmckinney's DM in Slack

**Comment by rsmckinney** [comment]
@dont-doubt thanks for tracking this down. The DM you sent to rsmckinney is not visible (a slack problem). Please DM to [@Scott](https://app.slack.com/client/T01385BBDLH/browse-people/rimeto_profile/U012VGGG1V0). Thanks.

**Comment by dont-doubt** [comment]
@rsmckinney  Done
