### ISSUE TITLE
using manifold together with error-prone

### ISSUE THREAD

**Issue by Xijie173** [manifold-systems/manifold#426]
hi, I'm trying to use google error-prone plugin together with manifold-ext plugin in my project, my maven-compiler-plugin is configured like this:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
        <fork>true</fork>
        <source>1.8</source>
        <target>1.8</target>
        <encoding>UTF-8</encoding>
        <showWarnings>true</showWarnings>
        <compilerArgs>
            <arg>-Xplugin:Manifold no-bootstrap</arg>
            <arg>-XDcompilePolicy=simple</arg>
            <arg>-Xplugin:ErrorProne -XepDisableWarningsInGeneratedCode</arg>
            <arg>-J-Xbootclasspath/p:${settings.localRepository}/com/google/errorprone/javac/9+181-r4173-1/javac-9+181-r4173-1.jar</arg>
        </compilerArgs>
        <annotationProcessorPaths>
            <path>
                <groupId>systems.manifold</groupId>
                <artifactId>manifold-ext</artifactId>
                <version>2023.1.3</version>
            </path>
            <path>
                <groupId>com.google.errorprone</groupId>
                <artifactId>error_prone_core</artifactId>
                <version>2.10.0</version>
            </path>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.24</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```
and I got this error:
```
Exception in thread "main" java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider manifold.internal.javac.JavacPluginBootstrap could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:209)
        at com.sun.tools.javac.main.Main.compile(Main.java:276)
        at com.sun.tools.javac.main.Main.compile(Main.java:162)
        at com.sun.tools.javac.Main.compile(Main.java:57)
        at com.sun.tools.javac.Main.main(Main.java:43)
Caused by: java.lang.ExceptionInInitializerError
        at manifold.internal.javac.JavacPluginBootstrap.<init>(JavacPluginBootstrap.java:37)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 7 more
Caused by: java.lang.NullPointerException
        at manifold.util.ReflectUtil$WithNull.method(ReflectUtil.java:1495)
        at manifold.util.ReflectUtil.method(ReflectUtil.java:279)
        at manifold.internal.javac.JavacPlugin.loadJavacParserClass(JavacPlugin.java:1418)
        at manifold.internal.javac.JavacPlugin.<clinit>(JavacPlugin.java:131)
        ... 14 more
```

JDK version: 1.8.0_242
Maven version: 3.5.0

any suggesstions? 🤔 
many thanks ❤️

**Comment by rsmckinney** [comment]
Older usage of error-prone required the javac compiler to load inside the bootstrap classloader, which doesn't play well with manifold. Newer error-prone releases generally integrate much better with javac using the annotation processor path, similar to how manifold works.

You can compile with the latest error-prone release using JDK 11+ and still target Java 8. I would suggest this route if it suits your needs.

Here is a sample Maven config I used to test compatibility with manifold.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Java8Project</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <manifold.version>2023.1.3</manifold.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>systems.manifold</groupId>
            <artifactId>manifold-ext-rt</artifactId>
            <version>${manifold.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                    <encoding>UTF-8</encoding>
                    <showWarnings>true</showWarnings>
                    <compilerArgs>
                        <arg>-XDcompilePolicy=simple</arg>
                        <arg>-Xplugin:ErrorProne</arg>
                        <arg>-Xplugin:Manifold</arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>2.18.0</version>
                        </path>
                        <path>
                            <groupId>systems.manifold</groupId>
                            <artifactId>manifold-ext</artifactId>
                            <version>${manifold.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by Xijie173** [comment]
I assume that means, if a project currently using jdk8, manifold won't work together with older error-prone plugin?
Is there any workaround for project using jdk8?

**Comment by rsmckinney** [comment]
I may be able to provide limited support. For example, looks like you’re using manifold-ext. That can probably work, but other aspects of manifold will not. If this sounds workable and you must use jdk 8 to compile your project, I’ll see about making this use-case work. 

Can I ask why a newer jdk isn’t in the cards?

**Comment by Xijie173** [comment]
Thanks a lot for your prompt reply. 
Our team is planning to migrate our jdk versions, but that takes time and there are some active projects currently works only on jdk8.
I'd be much appreciate if you can make this use case work. ❤️

**Comment by rsmckinney** [comment]
Hi @Xijie173. Just an FYI.

I was looking into making manifold work in an unlimited way with the older error-prone library. But what I found along the way is perhaps of interest to you, it was certainly a surprise to me.

Turns out he older error-prone lib loads a JDK 9 release into the bootstrap loader to compile your Java 8 project.
```xml
<arg>-J-Xbootclasspath/p:${settings.localRepository}/com/google/errorprone/javac/9+181-r4173-1/javac-9+181-r4173-1.jar</arg>
```
What's even stranger about this scenario, the Java 8 compiler is running with JDK 9 binaries.

I can probably work around this too, but I thought I'd let you know your project isn't really building with JDK 8, if you weren't already aware of this.  And, since you are already not using JDK 8, perhaps you'll reconsider compiling with JDK 11 and avoid the older error-prone oddities?  Just a thought.

**Comment by Xijie173** [comment]
Yes, google error-prone plugin archives jdk8 compatibility by adding a customized jdk9 version of javac.jar to bootstrap loader.
And thanks for your reminder, we only use error-prone plugin to check hidden issues, as the error-prone configuration is placed in a standalone profile, it will never be used to compile a release version.
I'm not really digging into the source code and checkout exactly what modification google had make, but according to its README, seems google had backport some feature to make this specific use case work, as you can check it out for yourself [here](https://github.com/google/error-prone-javac/tree/9+181-r4173-1), but since google gave up supporting (jdk8) years ago, this repo is archived too.
I guess google not only backports some changes that makes jdk9 incompatible with jdk8, but also doing some dev works to make them compatible, which may result in the incompatible of using manifold together with older error-prone.
