### ISSUE TITLE
NPE out of the blue while working with JS Files

### ISSUE THREAD

**Issue by mhossain419** [manifold-systems/manifold#50]
**Describe the bug**
While using IntelliJ version 2018.3.5 and working with JS files, I am experiencing periodical plugin crashes.

**Stack trace**
java.lang.NullPointerException
	at manifold.api.gen.SrcType.<init>(SrcType.java:53)
	at manifold.api.gen.SrcType.<init>(SrcType.java:48)
	at manifold.api.gen.SrcParameter.type(SrcParameter.java:62)
	at manifold.api.gen.SrcParameter.<init>(SrcParameter.java:39)
	at manifold.js.parser.tree.ParameterNode.toParamList(ParameterNode.java:54)
	at manifold.js.JavascriptProgram.makeSrcParameters(JavascriptProgram.java:86)
	at manifold.js.JavascriptProgram.genProgram(JavascriptProgram.java:72)
	at manifold.js.JavascriptCodeGen.make(JavascriptCodeGen.java:69)
	at manifold.js.JavascriptTypeManifold.contribute(JavascriptTypeManifold.java:55)
	at manifold.js.JavascriptTypeManifold.contribute(JavascriptTypeManifold.java:29)
	at manifold.api.type.ResourceFileTypeManifold.contribute(ResourceFileTypeManifold.java:377)
	at manifold.ij.extensions.ManifoldPsiClassCache.createPrimaryType(ManifoldPsiClassCache.java:238)
	at manifold.ij.extensions.ManifoldPsiClassCache.getPsiClass_NoShortCircuit(ManifoldPsiClassCache.java:132)
	at manifold.ij.extensions.ManifoldPsiClassCache._getPsiClass(ManifoldPsiClassCache.java:90)
	at manifold.ij.extensions.ManifoldPsiClassCache.getPsiClass(ManifoldPsiClassCache.java:78)
	at manifold.ij.extensions.ManShortNamesCache.findPsiClasses(ManShortNamesCache.java:65)
	at manifold.ij.extensions.ManShortNamesCache.findPsiClasses(ManShortNamesCache.java:47)
	at manifold.ij.extensions.ManShortNamesCache.getClassesByName(ManShortNamesCache.java:40)
	at com.intellij.psi.search.PsiShortNamesCache.processClassesWithName(PsiShortNamesCache.java:206)
	at com.intellij.psi.impl.CompositeShortNamesCache.processClassesWithName(CompositeShortNamesCache.java:262)
	at com.intellij.ide.util.gotoByName.DefaultClassNavigationContributor.processElementsWithName(DefaultClassNavigationContributor.java:114)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.lambda$getElementsByName$1(ContributorsBasedGotoByModel.java:174)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1163)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:99)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:391)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.ide.util.gotoByName.ContributorsBasedGotoByModel.getElementsByName(ContributorsBasedGotoByModel.java:210)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.processByNames(DefaultChooseByNameItemProvider.java:221)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:85)
	at com.intellij.ide.util.gotoByName.DefaultChooseByNameItemProvider.filterElements(DefaultChooseByNameItemProvider.java:45)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchElements$1(AbstractGotoSEContributor.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:539)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchElements(AbstractGotoSEContributor.java:86)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.lambda$run$1(MultiThreadSearcher.java:200)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ContributorSearchTask.run(MultiThreadSearcher.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.ConcurrencyUtil$3.run(ConcurrencyUtil.java:215)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rsmckinney** [comment]
Hi @mhossain419.

There are a couple of Javascript Manifold fixes coming with the next release (0.51-alpha), however I'm not sure if they address this specific issue.  Can you provide some context?  For instance, can you provide the JS file you were using when the exception appeared?  Also if you can provide steps to reproduce the issue, that would be great.

Thanks for reporting the issue!

> Note, the Javascript Manifold is still "experimental", as such it should be considered somewhat unstable until it graduates to a stable, supported Manifold component.

**Comment by mhossain419** [comment]
Hi @rsmckinney, 

The errors happen at random. Most recently it happened when I opened the find window and I was on Java file.

**Comment by mhossain419** [comment]
Crashed again while I was typing "private static final" in a java class. Stacktrace:

java.lang.RuntimeException: Incompatible types: Integer vs: rangeItem
	at manifold.api.json.Json.mergeTypes(Json.java:269)
	at manifold.api.json.JsonListType.merge(JsonListType.java:148)
	at manifold.api.json.JsonListType.merge(JsonListType.java:35)
	at manifold.api.json.Json.mergeTypesNoUnion(Json.java:302)
	at manifold.api.json.Json.mergeTypes(Json.java:251)
	at manifold.api.json.JsonStructureType.addMember(JsonStructureType.java:381)
	at manifold.api.json.Json.transformJsonObject(Json.java:170)
	at manifold.api.json.Json.transformJsonObject(Json.java:125)
	at manifold.api.json.Json.transformJsonObject(Json.java:167)
	at manifold.api.json.Json.transformJsonObject(Json.java:125)
	at manifold.api.json.Json.transformJsonObject(Json.java:167)
	at manifold.api.json.Json.transformJsonObject(Json.java:125)
	at manifold.api.json.Json.transformJsonObject(Json.java:194)
	at manifold.api.json.Json.transformJsonObject(Json.java:125)
	at manifold.api.json.Json.transformJsonObject(Json.java:167)
	at manifold.api.json.Json.transformJsonObject(Json.java:125)
	at manifold.api.json.Json.transformJsonObject(Json.java:167)
	at manifold.api.json.JsonModel.init(JsonModel.java:73)
	at manifold.api.json.JsonModel.<init>(JsonModel.java:48)
	at manifold.api.json.JsonTypeManifold.lambda$init$0(JsonTypeManifold.java:31)
	at manifold.api.type.ResourceFileTypeManifold.lambda$buildFqnToModelCache$0(ResourceFileTypeManifold.java:97)
	at manifold.util.concurrent.LocklessLazyVar$1.init(LocklessLazyVar.java:90)
	at manifold.util.concurrent.LocklessLazyVar.get(LocklessLazyVar.java:40)
	at manifold.api.type.ResourceFileTypeManifold.contribute(ResourceFileTypeManifold.java:376)
	at manifold.ij.extensions.ManifoldPsiClassCache.createPrimaryType(ManifoldPsiClassCache.java:238)
	at manifold.ij.extensions.ManifoldPsiClassCache.getPsiClass_NoShortCircuit(ManifoldPsiClassCache.java:132)
	at manifold.ij.extensions.ManifoldPsiClassCache._getPsiClass(ManifoldPsiClassCache.java:90)
	at manifold.ij.extensions.ManifoldPsiClassCache.getPsiClass(ManifoldPsiClassCache.java:78)
	at manifold.ij.extensions.ManShortNamesCache.findPsiClasses(ManShortNamesCache.java:65)
	at manifold.ij.extensions.ManShortNamesCache.findPsiClasses(ManShortNamesCache.java:47)
	at manifold.ij.extensions.ManShortNamesCache.getClassesByName(ManShortNamesCache.java:40)
	at com.intellij.psi.impl.CompositeShortNamesCache.getClassesByName(CompositeShortNamesCache.java:76)
	at com.intellij.psi.impl.search.AllClassesSearchExecutor.lambda$processClassesByNames$1(AllClassesSearchExecutor.java:68)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$0(DumbService.java:79)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:110)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:79)
	at com.intellij.psi.impl.search.AllClassesSearchExecutor.processClassesByNames(AllClassesSearchExecutor.java:68)
	at com.intellij.codeInsight.completion.AllClassesGetter.processJavaClasses(AllClassesGetter.java:136)
	at com.intellij.codeInsight.completion.AllClassesGetter.processJavaClasses(AllClassesGetter.java:122)
	at com.intellij.codeInsight.completion.JavaClassNameCompletionContributor.addAllClasses(JavaClassNameCompletionContributor.java:142)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.suggestNonImportedClasses(JavaNoVariantsDelegator.java:186)
	at com.intellij.codeInsight.completion.JavaNoVariantsDelegator.fillCompletionVariants(JavaNoVariantsDelegator.java:76)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:96)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at manifold.ij.extensions.ManJavaCompletionContributor.fillCompletionVariants(ManJavaCompletionContributor.java:25)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rsmckinney** [comment]
Ok I've reproduced this issue and have a fix which will be included in the next release (0.51-alpha), likely available early next week.  Thanks again for reporting this,
