### ISSUE TITLE
[Bug] `CsvTokenizerTest.testTypeInference()` fails when running `mvn clean package`

### ISSUE THREAD

**Issue by CC007** [manifold-systems/manifold#503]
**Describe the bug**
The test `CsvTokenizerTest.testTypeInference()` fails when running `mvn clean package`: 

```
...

[INFO] --- surefire:2.20:test (default-test) @ manifold-csv-test ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running manifold.csv.CsvTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.422 s - in manifold.csv.CsvTest
[INFO] Running manifold.csv.rt.CsvTokenizerTest
[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.092 s <<< FAILURE! - in manifold.csv.rt.CsvTokenizerTest
[ERROR] testTypeInference(manifold.csv.rt.CsvTokenizerTest)  Time elapsed: 0.005 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [6]; expected:<class java.time.LocalDate> but was:<class java.lang.String>
	at manifold.csv.rt.CsvTokenizerTest.testTypeInference(CsvTokenizerTest.java:188)
Caused by: java.lang.AssertionError: expected:<class java.time.LocalDate> but was:<class java.lang.String>
	at manifold.csv.rt.CsvTokenizerTest.testTypeInference(CsvTokenizerTest.java:188)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CsvTokenizerTest.testTypeInference:188 arrays first differed at element [6]; expected:<class java.time.LocalDate> but was:<class java.lang.String>
[INFO] 
[ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0
```
So for some reason the column doesn't get detected as a `LocalDate`.

**To Reproduce**
1. Fork manifold and checkout the master branch in IntelliJ
2. Set the SDK to java 8 (Zulu-8 used in this case)
3. Run mvn clean package

**Expected behavior**
All tests succeed and the build is successful.

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10
- Java/JDK version: Zulu-8 (1.8.0_232, vendor: Azul Systems, Inc.)
- maven version: 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c) 
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ 2023.2.2
- Manifold version: 2023.1.26-SNAPSHOT (latest master, commit: 9d2c5902)
- Manifold IntelliJ plugin version: 23.2.2

**Additional context**
When building with `@ignored` on that test, all other tests work without issue. When running the test with IntelliJ itself after that, I get the following message:
```
arrays first differed at element [6]; 
Expected :class java.time.LocalDate
Actual   :class java.lang.String
```

**Comment by rsmckinney** [comment]
Did not reproduce. Will close if no additional feedback.

**Comment by CC007** [comment]
I'll take another look
