### ISSUE TITLE
IntelliJ plugin bug: `NoClassDefFoundError: com/intellij/lang/java/parser/BasicStatementParser`

### ISSUE THREAD

**Issue by endorh** [manifold-systems/manifold#516]
**Describe the bug**
An exception is thrown by the Manifold IntelliJ IDEA plugin after opening a project:
> `java.lang.NoClassDefFoundError: com/intellij/lang/java/parser/BasicStatementParser`

No other adverse effects are appreciated. In particular, against what the stack trace could suggest, parsing and highlighting of Manifold directives within Manifold projects works as intended.

The exception doesn't seem to be thrown after opening a second project, so the actual trigger may be when the plugin first loads.

**To Reproduce**
1. Open any Gradle Java project (even one not using Manifold)
2. Observe the exception being reported by the IDE.

**Expected behavior**
No exception is thrown.

**Desktop:**
- OS Type & Version:
    `Windows 10.0 (Home)`
- Java/JDK version:
    `17.0.8.1+7-b1000.32 amd64`
    `OpenJDK 64-Bit Server VM by JetBrains s.r.o.`
- IDE version:
    `IntelliJ IDEA 2023.2.3 (Community Edition)`  (stable channel)
    `Build #IC-232.10072.27, built on October 11, 2023`
- Manifold version: 
    (Happens in non-Manifold projects, but, for the record:)
    `2023.1.27`
- Manifold IntelliJ plugin version: 
    `manifold.ij 2023.2.5`

**Additional context**
Before reporting this issue I tried updating IntelliJ to the latest version (2023.2.2 -> 2023.2.3), but it kept occurring. I also tried uninstalling and reinstalling the Manifold to ensure I was using the latest version form the Marketplace.

After the update, the Kotlin plugin has also started to throw a few exceptions on project load, but I don't think they're related.

**Stack trace**

<details>
<summary>See stack trace</summary>

```java-stacktrace
java.lang.NoClassDefFoundError: com/intellij/lang/java/parser/BasicStatementParser
	at manifold.ij.core.ManApplicationLoadListener.replaceJavaExpressionParser(ManApplicationLoadListener.java:147)
	at manifold.ij.core.ManApplicationLoadListener.overrideJavaParserStuff(ManApplicationLoadListener.java:86)
	at manifold.ij.core.ManApplicationLoadListener.beforeApplicationLoaded(ManApplicationLoadListener.java:65)
	at com.intellij.ide.bootstrap.AppPreInitKt$initConfigurationStore$2$1.invokeSuspend(appPreInit.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: com.intellij.lang.java.parser.BasicStatementParser PluginClassLoader(plugin=PluginDescriptor(name=Manifold, id=manifold.ij, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2023.2\plugins\manifold-ij, version=2023.2.5, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 10 more
```
</details>

**Comment by rsmckinney** [comment]
Working on this now. Was a bit difficult to track down, but will be fixed within 24 hours.  Thanks for reporting this!

**Comment by endorh** [comment]
I've just updated to the latest version from the marketplace and can confirm the fix works on my end. 🎉
That was quick, thanks for the fix. ^^

***
However, for the record, the first time I opened a project after the update I encountered the following rare exception, which I fixed by invalidating caches and can no longer reproduce, so I assume it's due to some obscure transitory inconsistency in the indices maybe caused by the update, as the message suggests:

> ```
> java.lang.Throwable: psiElement is not instance of requiredClass.
> psiElement=PsiReferenceList, psiElement.class=class com.intellij.psi.impl.source.PsiReferenceListImpl, requiredClass=interface com.intellij.psi.PsiClass.
> ref: 50cf572587cf
> com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
> Please report the problem to JetBrains with the files attached
> ```


Besides, the exception message states I should report this to JetBrains, so I don't think you have to worry about this one. 😄
If it somehow makes a reproducible comeback and JetBrains decides it's not their problem, I'll open a separate issue, but I doubt it'll happen.

<details>
<summary>(full stack trace)</summary>

```java-stack-trace
java.lang.Throwable: psiElement is not instance of requiredClass.
psiElement=PsiReferenceList, psiElement.class=class com.intellij.psi.impl.source.PsiReferenceListImpl, requiredClass=interface com.intellij.psi.PsiClass.
ref: 50cf572587cf
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: PSI and index do not match.
Please report the problem to JetBrains with the files attached
 file=PsiJavaFile:AerobaticElytraJeiPlugin.java, file.class=class com.intellij.psi.impl.source.PsiJavaFileImpl, file.lang=Language: JAVA, modStamp=0
 tree consistent
 stub debugInfo=created in calcStubTree; with backReference
 viewProvider=com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Users/david/Workspace/Games/Minecraft/Modding/Aerobatic Elytra/src/main/java/endorh/aerobaticelytra/integration/jei/AerobaticElytraJeiPlugin.java, vFileId=7056, content=VirtualFileContent{size=9197}, eventSystemEnabled=true}
 viewProvider stamp: 0; file stamp: 0; file modCount: 1697512765890; file length: 9197
 doc saved: true; doc stamp: 0; doc size: 9197; committed: true
indexing info: indexing timestamp = 1697512283620, binary = false, byte size = 9110, char size = 9197
ref: 50cf572587cf
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiJavaFileStub [endorh.aerobaticelytra.integration.jei]}951396320
   same size=false
   debugInfo=created from index; with backReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.psi.stubs.StubProcessingHelperBase.inconsistencyDetected(StubProcessingHelperBase.java:164)
	at com.intellij.psi.stubs.StubProcessingHelperBase.checkType(StubProcessingHelperBase.java:99)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:72)
	at com.intellij.psi.stubs.StubIndexEx.lambda$processElements$4(StubIndexEx.java:150)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:214)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:34)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:81)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:104)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:40)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:94)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:72)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:443)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.access$100(PsiJavaCodeReferenceElementImpl.java:44)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:378)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl$OurGenericsResolver.resolve(PsiJavaCodeReferenceElementImpl.java:371)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:174)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:174)
	at manifold.ij.extensions.ManResolveCache.resolveWithCaching(ManResolveCache.java:88)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:846)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:838)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:814)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:426)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:420)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.resolve(PsiJavaCodeReferenceElementImpl.java:355)
	at com.intellij.psi.impl.source.PsiImportStatementBaseImpl.resolve(PsiImportStatementBaseImpl.java:61)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.findExplicitDeclarations(PsiJavaFileBaseImpl.java:355)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.lambda$getEnumeratedDeclarations$0(PsiJavaFileBaseImpl.java:339)
	at com.intellij.openapi.util.NotNullLazyValue$4.compute(NotNullLazyValue.java:120)
	at com.intellij.openapi.util.NotNullLazyValue$4.getValue(NotNullLazyValue.java:105)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.lambda$getEnumeratedDeclarations$1(PsiJavaFileBaseImpl.java:340)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:813)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.processDeclarations(PsiJavaFileBaseImpl.java:289)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:61)
	at com.intellij.psi.scope.util.PsiScopesUtil.treeWalkUp(PsiScopesUtil.java:40)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:207)
	at com.intellij.psi.scope.util.PsiScopesUtil.resolveAndWalk(PsiScopesUtil.java:136)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolveToVariable(PsiReferenceExpressionImpl.java:332)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:242)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.access$000(PsiReferenceExpressionImpl.java:44)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:182)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:172)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:174)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:174)
	at manifold.ij.extensions.ManResolveCache.resolveWithCaching(ManResolveCache.java:88)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver$1.elementFinished(PsiReferenceExpressionImpl.java:221)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor$1.elementFinished(JavaRecursiveElementWalkingVisitor.java:35)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor$1.elementFinished(JavaRecursiveElementWalkingVisitor.java:32)
	at com.intellij.util.WalkingState.next(WalkingState.java:96)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:51)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:42)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:62)
	at com.intellij.psi.JavaRecursiveElementWalkingVisitor.visitElement(JavaRecursiveElementWalkingVisitor.java:41)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver$1.visitReferenceExpression(PsiReferenceExpressionImpl.java:214)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:777)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolveAllQualifiers(PsiReferenceExpressionImpl.java:204)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:181)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl$OurGenericsResolver.resolve(PsiReferenceExpressionImpl.java:172)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolveWithCaching$2(ResolveCache.java:174)
	at com.intellij.openapi.util.Computable.get(Computable.java:16)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:234)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:27)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:65)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:212)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:174)
	at manifold.ij.extensions.ManResolveCache.resolveWithCaching(ManResolveCache.java:88)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:846)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:838)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:814)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.multiResolve(PsiReferenceExpressionImpl.java:338)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.advancedResolve(PsiReferenceExpressionImpl.java:491)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.resolve(PsiReferenceExpressionImpl.java:798)
	at com.demonwav.mcdev.translations.identification.ReferenceTranslationIdentifier.identify(ReferenceTranslationIdentifier.kt:34)
	at com.demonwav.mcdev.translations.identification.ReferenceTranslationIdentifier.identify(ReferenceTranslationIdentifier.kt:32)
	at com.demonwav.mcdev.translations.identification.TranslationIdentifier.identifyUnsafe(TranslationIdentifier.kt:36)
	at com.demonwav.mcdev.translations.TranslationFoldingBuilder.buildFoldRegions(folding.kt:93)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.CompositeFoldingBuilder.buildFoldRegions(CompositeFoldingBuilder.java:41)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptorsNoPlaceholderCaching(LanguageFolding.java:92)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:74)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:272)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:240)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.buildInitialFoldings(CodeFoldingManagerImpl.java:138)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2$1$1.invoke(PsiAwareTextEditorImpl.kt:78)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2$1$1.invoke(PsiAwareTextEditorImpl.kt:77)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator$lambda$1(coroutines.kt:386)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator(coroutines.kt:374)
	at com.intellij.openapi.progress.CoroutinesKt.contextToIndicator(coroutines.kt:347)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextToIndicator(coroutines.kt:340)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2.invoke(PsiAwareTextEditorImpl.kt:77)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl$loadEditorInBackground$2.invoke(PsiAwareTextEditorImpl.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:105)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:39)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:37)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:34)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:76)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:63)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:14)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:42)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:38)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground$suspendImpl(PsiAwareTextEditorImpl.kt:74)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.loadEditorInBackground(PsiAwareTextEditorImpl.kt)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader$start$continuationDeferred$1.invokeSuspend(AsyncEditorLoader.kt:116)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
</details>
