### ISSUE TITLE
cpu 100% when use manifold sql fetch()

### ISSUE THREAD

**Issue by pinksmallpig** [manifold-systems/manifold#543]
**Describe the bug**
idea no response and cpu 100% when I try to use new feature manifold-sql . I try to kill idea process and restart but it still no response cause idea cant init complete.

**To Reproduce**
1.new Test class and main method
2.write "[.sql/] select * from sys_user"
3.type . after sql

**Expected behavior**
show method tips.

**Desktop (please complete the following information):**
- OS Type & Version: Windows10  professional 20H2
- Java/JDK version: OpenJDK17
- IDE version (IntelliJ IDEA or Android Studio): 2023.2.3
- Manifold version: 2024.1.1
- Manifold IntelliJ plugin version:  2023.1.37

**Stack trace**
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: manifold.rt.api.ScriptException: Found errors:
[6:1] expecting 'a string', found '}'
[6:1] expecting ':', found 'EOF'
[6:1] Unexpected token 'EOF'
[6:1] expecting '}', found 'EOF'

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:672)
	at com.intellij.concurrency.JobLauncherImpl.processQueue(JobLauncherImpl.java:375)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.processInOrder(InspectionRunner.java:310)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.visitElements(InspectionRunner.java:285)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.lambda$inspect$4(InspectionRunner.java:129)
	at com.intellij.codeInspection.InspectionEngine.withSession(InspectionEngine.java:227)
	at com.intellij.codeInsight.daemon.impl.InspectionRunner.inspect(InspectionRunner.java:115)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:95)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: manifold.rt.api.ScriptException: Found errors:
[6:1] expecting 'a string', found '}'
[6:1] expecting ':', found 'EOF'
[6:1] Unexpected token 'EOF'
[6:1] expecting '}', found 'EOF'

	at manifold.sql.schema.type.SchemaManifold.getTypeNameForFile(SchemaManifold.java:71)
	at manifold.api.type.ResourceFileTypeManifold.buildPrimaryFqnToFilesMap(ResourceFileTypeManifold.java:165)
	at manifold.api.type.ResourceFileTypeManifold.buildFqnToModelCache(ResourceFileTypeManifold.java:96)
	at manifold.util.concurrent.LocklessLazyVar$1.init(LocklessLazyVar.java:91)
	at manifold.util.concurrent.LocklessLazyVar.get(LocklessLazyVar.java:40)
	at ma

**Comment by rsmckinney** [comment]
Hi @pinksmallpig. The manifold plugin release (2023.1.37) you are using is old and not compatible with your IJ release (2023.2.3). Please use manifold plugin release **2023.2.14** or greater. You should be able to update it automatically in IDE plugin settings.

**Comment by fionalde** [comment]
java.lang.RuntimeException: java.lang.RuntimeException: manifold.rt.api.ScriptException: Found errors:
[8:1] expecting 'a string', found '}'
[8:1] expecting ':', found 'EOF'
[8:1] Unexpected token 'EOF'
[8:1] expecting '}', found 'EOF'

	at manifold.sql.schema.type.SchemaManifold.getTypeNameForFile(SchemaManifold.java:71)
	at manifold.api.type.ResourceFileTypeManifold.buildPrimaryFqnToFilesMap(ResourceFileTypeManifold.java:165)
	at manifold.api.type.ResourceFileTypeManifold.buildFqnToModelCache(ResourceFileTypeManifold.java:96)
	at manifold.util.concurrent.LocklessLazyVar$1.init(LocklessLazyVar.java:91)
	at manifold.util.concurrent.LocklessLazyVar.get(LocklessLazyVar.java:40)
	at manifold.api.type.ResourceFileTypeManifold.getAllTypeNames(ResourceFileTypeManifold.java:445)
	at manifold.api.type.ResourceFileTypeManifold.getTypeNames(ResourceFileTypeManifold.java:457)
	at manifold.api.type.ResourceFileTypeManifold.isPackage(ResourceFileTypeManifold.java:373)
	at manifold.ij.extensions.ManTypeFinder.findPackage(ManTypeFinder.java:288)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findPackage(JavaPsiFacadeImpl.java:211)
	at com.intellij.psi.impl.file.JavaDirectoryServiceImpl.getPackage(JavaDirectoryServiceImpl.java:50)
	at com.intellij.ide.projectView.impl.JavaProjectViewDirectoryHelper.getNodeName(JavaProjectViewDirectoryHelper.java:59)
	at com.intellij.ide.projectView.impl.nodes.PsiDirectoryNode.updateImpl(PsiDirectoryNode.java:139)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:214)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction$lambda$3(AnyThreadWriteThreadingSupport.kt:258)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:272)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runReadAction(AnyThreadWriteThreadingSupport.kt:258)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:853)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:167)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:163)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:171)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:129)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:118)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:108)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:163)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:32)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:540)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:521)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:514)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:432)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:332)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:326)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:348)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.computeNode(AsyncTreeModel.java:668)
	at com.intellij.ui.tree.AsyncTreeModel$Command.computeNode(AsyncTreeModel.java:541)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:361)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.run(CoroutineInvokerDelegate.kt:38)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:189)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:173)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:470)
	at com.intellij.util.concurrency.CoroutineInvokerDelegate.offer$lambda$2(CoroutineInvokerDelegate.kt:27)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1.invokeSuspend$lambda$1$lambda$0(CoroutineInvokerDelegate.kt:97)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate.withProperContext$lambda$0(CoroutineInvokerDelegate.kt:73)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.util.concurrency.BgtCoroutineInvokerDelegate.withProperContext(CoroutineInvokerDelegate.kt:72)
	at com.intellij.util.concurrency.SequentialBgtCoroutineInvokerDelegate$doLaunch$1.invokeSuspend(CoroutineInvokerDelegate.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.RuntimeException: manifold.rt.api.ScriptException: Found errors:
[8:1] expecting 'a string', found '}'
[8:1] expecting ':', found 'EOF'
[8:1] Unexpected token 'EOF'
[8:1] expecting '}', found 'EOF'

	at manifold.json.rt.Json.fromJson(Json.java:303)
	at manifold.json.rt.Json.fromJson(Json.java:293)
	at manifold.sql.schema.type.SchemaManifold.getTypeNameForFile(SchemaManifold.java:58)
	... 75 more
Caused by: manifold.rt.api.ScriptException: Found errors:
[8:1] expecting 'a string', found '}'
[8:1] expecting ':', found 'EOF'
[8:1] Unexpected token 'EOF'
[8:1] expecting '}', found 'EOF'

	at manifold.json.rt.parser.DefaultParser.parseJson(DefaultParser.java:48)
	at manifold.json.rt.Json.fromJson(Json.java:299)
	... 77 more

In the idea community version 24.3.11 and plug-in version 24.1.17, this problem still occurs, and the cpu utilization rate reaches more than 90%
