### ISSUE TITLE
Spring Cloud Stream throws exception when converting a message to a manifold created object from JSON

### ISSUE THREAD

**Issue by dakotahNorth** [manifold-systems/manifold#572]
Spring Cloud Stream can't automatically convert a manifold created object from JSON to POJO. 

First the code with a POJO called `Person` ... 

```
package com.example.helloworldspringcloudstream;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.function.Consumer;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.stream.function.StreamBridge;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class HelloWorldSpringCloudStreamApplication {

    public static void main(String... args) {
        SpringApplication.run(HelloWorldSpringCloudStreamApplication.class, args);

    }

    @Bean
    public Consumer<Person> exampleEventConsumer() {

        return event -> {
            System.out.println("Received event: " + event.getName());

        };

    }


}
```

And the `Person` POJO in `Person.Java` : 

```
package com.example.helloworldspringcloudstream;

public class Person {

    private String name;

    public Person() { }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


}
```

The above works as expected ... a JSON message that is sent into the broker is automically converted to a `Person` object. 

Then, swapping in `PersonManifold` from JSON 

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://com.example.helloworldspringcloudstream.PersonManifold.json",
  "title": "PersonManifold",
  "type": "object",
  "properties": {
    "name": { "type": "string" }
  }

}
```

And corresponding change in callback ... 

```
    @Bean
    public Consumer<PersonManifold> exampleEventConsumer() {

        return event -> {
            System.out.println("Received event: " + event.getName());

        };

    }

```

And sending the same message as above, results in a failure to convert the message: 

```
2024-04-16T11:25:30.927-04:00  WARN 47125 --- [HelloWorldSpringCloudStream] [pool-3-thread-1] c.s.s.c.s.b.i.JCSMPInboundChannelAdapter : Failed to consume a message from destination #P2P/QTMP/v:vzk7e2ikt35primary/scst/an/bbe6e438-7852-45c5-97f0-f8d1aa8bc466/plain/try-me - attempt 3
2024-04-16T11:25:30.933-04:00 ERROR 47125 --- [HelloWorldSpringCloudStream] [pool-3-thread-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.function.FunctionConfiguration$FunctionToDestinationBinder$1@626467d0], failedMessage=GenericMessage [payload=byte[23], headers={solace_expiration=0, solace_destination=try-me, solace_replicationGroupMessageId=rmid1:30704-81ae9045b12-00000000-0000018d, deliveryAttempt=3, solace_isReply=false, solace_timeToLive=0, solace_receiveTimestamp=0, acknowledgmentCallback=com.solace.spring.cloud.stream.binder.inbound.acknowledge.JCSMPAcknowledgementCallback@676475b6, solace_discardIndication=false, solace_dmqEligible=false, solace_priority=-1, solace_redelivered=false, id=bd72984f-5f2c-d352-2710-85a3809c0e97, contentType=application/json, timestamp=1713281127830}]


Caused by: java.lang.RuntimeException: Receiver type 'byte[]' does not implement a method structurally compatible with method: public abstract java.lang.String com.example.helloworldspringcloudstream.PersonManifold.getName()
	at manifold.util.ReflectUtil.structuralCallByProxy(ReflectUtil.java:1605)
	at manifold.ext.rt.RuntimeMethods.lambda$null$7(RuntimeMethods.java:435)
	at jdk.proxy2/com.sun.proxy.jdk.proxy2.$ManProxy0.getName(Unknown Source)
```

**Comment by rsmckinney** [comment]
The problem is probably related to `PersonManifold` being an interface, Spring Cloud Stream can't create an instance of it.

**Comment by rsmckinney** [comment]
I'm pretty confident the issue with PersonManifold is due to the fact that it's an interface, spring needs a concrete class to construct.

I don't use spring, however I took a brief look and it appears you may be able to provide a custom binder so you can override handleMessage() and do whatever you like.  That being the case, you could implement bindings for manifold-json, something like this:
```java
Class<?> beanClass = get json interface from spring;
String jsonString = new String(jsonByteArray);
Object jsonObj = manifold.json.rt.Json.fromJson(jsonString);
beanClass obj = manifold.ext.rt.RuntimeMethods.coerce(jsonObj, beanClass); 
return obj;
```
With this in place your original exampleEventConsumer example should work.
