### ISSUE TITLE
ItelliJ IDEA 2024.1 exception in plugin Manifold 2023.3.24

### ISSUE THREAD

**Issue by walth** [manifold-systems/manifold#574]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'manifold.ij.actions.ViewJavaSourceAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: manifold.ij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

![image](https://github.com/manifold-systems/manifold/assets/5897576/e6894803-4cd3-4174-9d20-43806e1eb9c3)

**Comment by Enaium** [comment]
same here

**Comment by rsmckinney** [comment]
Fix available with latest plugin releases (2023.3.25, 2023.2.25, 2023.1.47)
