### ISSUE TITLE
bypassJava9Security failing with NPE

### ISSUE THREAD

**Issue by apkulick** [manifold-systems/manifold#619]
**Describe the bug**
`NecessaryEvilUtil.bypassJava9Security` is failing with a NullPointerException when executed within the context of a SonarQube plugin.

**To Reproduce**
1. Create a SonarQube plugin using the manifold library
2. Run plugin using Sonar Scanner CLI v5

I'm still working on trying to reproduce this outside of the context of a Sonar Scan, but have been unsuccessful. Sonar Scanner CLI does do things to create custom class loaders so I wonder if that may be part of the issue

**Expected behavior**
`NecessaryEvilUtil.bypassJava9Security` runs without errors

**Screenshots**
none

**Desktop (please complete the following information):**
- OS Type & Version: Linux a0ce0dffe318 6.5.0-1024-aws 24~22.04.1-Ubuntu SMP Thu Jul 18 10:43:12 UTC 2024 x86_64 Linux
- Java/JDK version: openjdk 17.0.10 2024-01-16
- IDE version (IntelliJ IDEA or Android Studio): n/a 
- Manifold version: 2024.1.19 (dependency of `gosu-core-api` 1.18.1)
- Manifold IntelliJ plugin version: n/a

**Additional context**

We have built a custom SonarQube plugin for the Gosu language, specifically using the `gosu-core-api` and `gosu-core` libraries found [here](https://github.com/gosu-lang/gosu-lang). The plugin has run fine against a SonarQube 9.x instance using the Sonar Scanner CLI image v4 found [here](https://hub.docker.com/r/sonarsource/sonar-scanner-cli). The v4 scanner image has a Java runs with the following Java version:

```
openjdk 11.0.20 2023-07-18
OpenJDK Runtime Environment (build 11.0.20+8-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.20+8-alpine-r0, mixed mode)
```

Upgrading to SonarQube v10, requires the use of Sonar Scanner CLI v5 which has the following Java version which leads to the error shown in the Stack Trace section.

```
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-alpine-r0)
OpenJDK 64-Bit Server VM (build 17.0.10+7-alpine-r0, mixed mode, sharing)
```

Additionally, Scanner v5 was run with the following Java options to deal with errors that had occurred before this one: `--add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/jdk.compiler=ALL-UNNAMED`

**Stack trace**
```
java.lang.RuntimeException: Error initializing Manifold
	at manifold.util.NecessaryEvilUtil.openModules(NecessaryEvilUtil.java:118)
	at manifold.util.NecessaryEvilUtil.bypassJava9Security(NecessaryEvilUtil.java:59)
	at manifold.util.NecessaryEvilUtil.bypassJava9Security(NecessaryEvilUtil.java:54)
	at gw.lang.Gosu.init(Gosu.java:351)
	at com.nationwide.sonar.plugins.gosu.GosuSensor.execute(GosuSensor.java:166)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:204)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:200)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:173)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.SpringScannerContainer.doAfterStart(SpringScannerContainer.java:351)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:144)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at manifold.util.ReflectUtil$MethodRef.invoke(ReflectUtil.java:946)
	at manifold.util.NecessaryEvilUtil.openCompilerModules(NecessaryEvilUtil.java:160)
	at manifold.util.NecessaryEvilUtil.openModules(NecessaryEvilUtil.java:113)
	... 37 more
```

**Comment by rsmckinney** [comment]
You might try modifying your build file to turn off bootstrapping: `-Xplugin:Manifold no-bootstrap`.   Of course this is just a workaround, but it may solve your problem. If you can reproduce this outside of Sonar Scan, that would be great.

**Comment by apkulick** [comment]
Found the root of the problem. The Sonar Scanner v5 image only has a JRE in it. Creating an image that has a full JDK solved the error above. Thanks for the bit here:

```
After a bit more thought, the problem could be that your specific Java runtime does not include the jdk.compiler module.
```

It sent me down the path if investigating what was installed in the image I was using.
