### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by danny-su** [manifold-systems/manifold#649]
This issue happens very often, and I have to kill the Gradle daemon process to rebuild my projects. Otherwise, it will always fail.
My macOS has enough memory.
![PixPin_2024-12-16_18-09-51](https://github.com/user-attachments/assets/54685395-0f05-4795-95f3-565261b26630)

```
> Task :orderprocessing-core:compileJava
编译器 (21.0.5) 中出现异常错误。如果在 Bug Database (https://bugs.java.com) 中没有找到有关该错误的 Java 编译器 Bug，请通过 Java Bug 报告页 (https://bugreport.java.com) 提交 Java 编译器 Bug。请在报告中附上您的程序、以下诊断信息以及传递到 Java 编译器的参数。谢谢。
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.iterator(ArrayList.java:1029)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:451)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:349)
	at java.base/java.util.jar.JarFile.getBytes(JarFile.java:817)
	at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:1027)
	at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:387)
	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:509)
	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:743)
	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:858)
	at manifold.api.fs.jar.JarFileDirectoryImpl.getInputStream(JarFileDirectoryImpl.java:137)
	at manifold.api.fs.jar.JarEntryFileImpl.openInputStream(JarEntryFileImpl.java:40)
	at manifold.api.fs.Extensions.getExtensions(Extensions.java:59)
	at manifold.api.fs.Extensions.getExtensions(Extensions.java:39)
	at manifold.api.fs.IFileUtil.hasSourceFiles(IFileUtil.java:84)
	at manifold.api.fs.cache.PathCache.init(PathCache.java:65)
	at manifold.api.fs.cache.PathCache.<init>(PathCache.java:56)
	at manifold.internal.host.SimpleModule.makePathCache(SimpleModule.java:213)
	at manifold.internal.host.SimpleModule$$Lambda/0x0000000601651fe0.init(Unknown Source)
	at manifold.util.concurrent.LocklessLazyVar$1.init(LocklessLazyVar.java:91)
	at manifold.util.concurrent.LocklessLazyVar.get(LocklessLazyVar.java:40)
	at manifold.internal.host.SimpleModule.getPathCache(SimpleModule.java:127)
	at manifold.api.type.ResourceFileTypeManifold.buildPrimaryFqnToFilesMap(ResourceFileTypeManifold.java:150)
	at manifold.api.type.ResourceFileTypeManifold.buildFqnToModelCache(ResourceFileTypeManifold.java:96)
	at manifold.api.type.ResourceFileTypeManifold$$Lambda/0x0000000601656d18.init(Unknown Source)
	at manifold.util.concurrent.LocklessLazyVar$1.init(LocklessLazyVar.java:91)
	at manifold.util.concurrent.LocklessLazyVar.get(LocklessLazyVar.java:40)
	at manifold.api.type.ResourceFileTypeManifold.getAllTypeNames(ResourceFileTypeManifold.java:445)
	at manifold.api.type.ResourceFileTypeManifold.getTypeNames(ResourceFileTypeManifold.java:457)
	at manifold.internal.host.SimpleModule.getChildrenOfNamespace(SimpleModule.java:205)
	at manifold.internal.javac.ManifoldJavaFileManager.list(ManifoldJavaFileManager.java:229)
	at jdk.compiler/com.sun.tools.javac.code.ClassFinder.list(ClassFinder.java:752)

> Task :orderprocessing-core:compileJava FAILED


```

**Comment by chirag-scaletech** [comment]
java -Xms512m -Xmx2g -jar your-application.jar

-Xms512m: Sets the initial heap size to 512MB.
-Xmx2g: Sets the maximum heap size to 2GB.
Adjust the values based on your application requirements and system capacity.
