### ISSUE TITLE
JDK plugin configuration cause NullPointerException bug

### ISSUE THREAD

**Issue by mouthwatering** [manifold-systems/manifold#65]
**Describe the bug**

**To Reproduce**
1. configura the maven-resources-plugin compiler args by adding.
```
   <compilerArgs>

              <!-- Add the Manifold plugin, with string templates and checked exception suppression enabled -->
              <!--<arg>-Xplugin:Manifold strings exceptions</arg>-->
              <arg>-Xplugin:Manifold strings</arg>
            </compilerArgs>
```
Other configuration related to JDK 8, I have followed the set up instructions.
2. run a hello world project created by myself.
3. When do mvn compile, I got a null pointer exception.
4. If I commented Manifold configurations JDK8 in pom.xml and comment Manifold related code, my project compiles and runs successfuly. so I think there is something wrong with this part or the manifold plugin or other manifold configuration. Could you help take a look?

![Capture](https://user-images.githubusercontent.com/3627746/56015502-d3ce4b80-5d2b-11e9-88a5-e8416522aabf.PNG)

**Expected behavior**
We expect the project to be compiled successfuly

**Screenshots**
If applicable, add screenshots to help explain your problem (drag/drop them here).

**Desktop (please complete the following information):**
- OS Type & Version: Windows Server 2017 Datacenter
- Java/JDK version: 1.8.0_131
- IntelliJ IDEA version: 2018.3.2
- Manifold version:0.59-alpha
- Manifold IntelliJ plugin version: 0.59-alpha

**Additional context**

**Stack trace**
Please include a stack trace if applicable
An exception has occurred in the compiler (1.8.0_131). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:473)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at manifold.internal.javac.JavacPlugin.injectManFileManager(JavacPlugin.java:445)
	at manifold.internal.javac.JavacPlugin.hijackJavacFileManager(JavacPlugin.java:306)
	at manifold.internal.javac.JavacPlugin.init(JavacPlugin.java:172)
	at com.sun.tools.javac.main.Main.compile(Main.java:470)
	... 29 more
Caused by: java.lang.NullPointerException
	at manifold.util.concurrent.ConcurrentWeakHashMap.get(ConcurrentWeakHashMap.java:1009)
	at manifold.util.ReflectUtil.getRawMethodFromCache(ReflectUtil.java:710)
	at manifold.util.ReflectUtil.getMethodFromCache(ReflectUtil.java:700)
	at manifold.util.ReflectUtil.method(ReflectUtil.java:156)
	at manifold.internal.javac.JavacPlugin.injectManFileManager(JavacPlugin.java:413)
	... 32 more

**Comment by rsmckinney** [comment]
Hi @mouthwatering.  Can you provide a link to your hello world project?  I can diagnose it directly for you. Also you can use the [the sample app](https://github.com/manifold-systems/manifold-sample-project) as a reference, paying close attention to the Java 8 portions of the pom file.

**Comment by rsmckinney** [comment]
Also your version of Java is a bit old (131), that's probably not the cause, but you might consider downloading a newer version if possible.

**Comment by mouthwatering** [comment]
Thank you for you quick response! I fixed this bug by add 
```
<source>1.8</source>
            <target>1.8</target>
```

as configuration for maven-compiler-plugin

**Comment by rsmckinney** [comment]
No problem. Thanks for the feedback.
