### ISSUE TITLE
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.java.PsiThisExpressionImpl cannot be cast to com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl

### ISSUE THREAD

**Issue by RaviH** [manifold-systems/manifold#70]
**Describe the bug**
Using Manifold plugin with IntelliJ 2019.1 causes the error below:

```
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.java.PsiThisExpressionImpl cannot be cast to com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl
```
**NOTE**: The project still builds fine but these errors happen constantly.

Full stack trace:

```
In file: file:///Users/rhasija/dev/projects/lineup/lineup-cache-service/core/src/main/java/com/charter/lineup/cache/service/core/cache/twc/VodProviderCacheKey.java

java.lang.ClassCastException: com.intellij.psi.impl.source.tree.java.PsiThisExpressionImpl cannot be cast to com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl
	at manifold.ij.extensions.ManHighlightInfoFilter.filterCannotAssignToFinalIfJailbreak(ManHighlightInfoFilter.java:198)
	at manifold.ij.extensions.ManHighlightInfoFilter.accept(ManHighlightInfoFilter.java:97)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightInfoHolder.accepted(HighlightInfoHolder.java:105)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightInfoHolder.add(HighlightInfoHolder.java:56)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitExpression(HighlightVisitorImpl.java:549)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visitAssignmentExpression(HighlightVisitorImpl.java:314)
	at com.intellij.psi.impl.source.tree.java.PsiAssignmentExpressionImpl.accept(PsiAssignmentExpressionImpl.java:106)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.visit(HighlightVisitorImpl.java:136)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.lambda$analyze$2(HighlightVisitorImpl.java:161)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:370)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:160)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**To Reproduce**
1. I would venture to guess this should be reproducible with a simple manifold project with `strings, exceptions` 
2. My pom.xml, maven-compiler-plugin

```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.7.0</version>
                    <configuration>
                        <source>${jdk.version}</source>
                        <target>${jdk.version}</target>
                        <compilerArgs>
                            <arg>-parameters</arg>
                            <arg>-Xplugin:Manifold strings exceptions</arg>
                        </compilerArgs>

                        <annotationProcessorPaths>

                            <path>
                                <groupId>systems.manifold</groupId>
                                <artifactId>manifold</artifactId>
                                <version>${manifold.version}</version>
                            </path>
                            <path>
                                <groupId>systems.manifold</groupId>
                                <artifactId>manifold-ext</artifactId>
                                <version>${manifold.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <groupId>io.micronaut</groupId>
                                <artifactId>micronaut-inject-java</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                            <path>
                                <groupId>io.micronaut</groupId>
                                <artifactId>micronaut-inject-groovy</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                            <path>
                                <groupId>io.micronaut.configuration</groupId>
                                <artifactId>micronaut-openapi</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                            <path>
                                <groupId>io.micronaut</groupId>
                                <artifactId>micronaut-validation</artifactId>
                                <version>${micronaut.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/141136/56852623-58939a80-68d2-11e9-8fad-dbdacf4767a1.png)

**Desktop (please complete the following information):**
- OS Type & Version: MacOS High Sierra: 10.13.6
- Java/JDK version: java version "1.8.0_162"
- IntelliJ IDEA version: 2019.1
- Manifold version: 0.59-alpha
- Manifold IntelliJ plugin version: 0.59-alpha

**Additional context**
Happens while regular project building.

**Comment by rsmckinney** [comment]
Fix is ready for next plugin release.  Thanks for reporting this!

**Comment by rsmckinney** [comment]
ad7766d1 scott on 4/19/2019 at 11:39 PM
